version: '3.1'
services:
  motodtp:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: motodtp
    ports:
      - "433:433"
    environment:
      - SERVER_PORT=433
      - MONGODB=mongodb://mongo:27017/
    depends_on:
      - mongo
  mongo:
    image: mvertes/alpine-mongo
    ports:
      - "27019:27017"
    logging:
      driver: none