spring:
  data:
    mongodb:
      uri: ${MONGODB:mongodb://localhost:27017}
      database: ${MONGODB_NAME:motodtp}
  mvc:
    log-request-details: true

motodtp:
  security:
    jwtSecret: ${JWT_SECRET:b7njzm4937NGM@ONdyueoxnBJDg47r78}
  vk:
    appId: ${VK_APP_ID:111111}
    apiVersion: "5.130"
    redirectUrl: ${VK_REDIRECT_URL:http://localhost}
    tokenUrl: https://oauth.vk.com/access_token
    dataUrl: https://api.vk.com/method/users.get
    secret: ${VK_APP_SECRET:aaaaa}

server:
  ssl:
    key-store-type: PKCS12
    key-store: ${KEYSTORE:classpath:keystore/backend_test.p12}
    key-store-password: ${KEY_PASSWORD:123456}
    key-alias: ${KEY_ALIAS:backend_test}
    enabled: true

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
